refresh_rate: 30 seconds
appenders:
  stdout-appender:
    kind: console
  file-appender:
    kind: file
    path: "log/ppaass-proxy.log"
    encoder:
      pattern: "{l} {d(%Y-%m-%d#%H:%M:%S)} {f}:{L} - {m}{n}"
root:
  level: debug
  appenders:
    - file-appender
loggers:
  main:
    level: debug
    appenders:
      - file-appender
    additive: false