compress = true
dst_connect_timeout = 20
dst_tcp_buffer_size = 65536
ipv6 = false
agent_recive_buffer_size = 65536
port = 80
worker_thread_number = 128
rsa_dir = "./resources/rsa/"
dst_udp_recv_timeout = 5
dst_udp_connect_timeout = 5
agent_relay_timeout = 7200
dst_relay_timeout = 7200
