refresh_rate: 30 seconds
appenders:
  stdout-appender:
    kind: console
  file-appender:
    kind: file
    path: "log/ppaass-agent.log"
    encoder:
      pattern: "{l} {d(%Y-%m-%d %H:%M:%S)} {L} {I} - {m}{n}"
root:
  level: info
  appenders:
    - file-appender
loggers:
  main:
    level: info
    appenders:
      - file-appender
    additive: false