[workspace]
members = ["proxy", "agent-android", "agent-desktop", "protocol", "common", "io"]
[workspace.package]
authors = ["Hao Qu"]
description = "A security network channel"
documentation = "https://github.com/quhxuxm/ppaass"
version = "0.1.0"
[workspace.dependencies]
aes = "*"
anyhow = "*"
base64 = "*"
blowfish = "*"
bytes = "*"
cipher = "*"
clap = "*"
ecb = {version = "*", features = ["std"]}
futures = "*"
futures-util = "*"
lz4 = "*"
pin-project = "*"
pretty-hex = "*"
rand = "*"
rsa = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
thiserror = "*"
tokio = "*"
tokio-util = "*"
toml = "*"
tracing = "*"
uuid = {version = "*", features = ["v4"]}
