[workspace]
members = ["proxy", "agent-android", "agent-desktop", "protocol", "common"]
[workspace.package]
authors = ["Hao Qu"]
description = "A security network channel"
documentation = "https://github.com/quhxuxm/ppaass"
version = "0.1.0"
[workspace.dependencies]
aes = "*"
base64 = "*"
blowfish = "*"
bytes = "*"
cipher = "*"
ecb = {version = "*", features = ["std"]}
futures = "*"
futures-util = {version = "*", features = ["alloc"]}
rand = "*"
rsa = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
thiserror = "*"
tokio = {version = "*", features = ["time", "net"]}
tokio-util = {version = "*", features = ["codec"]}
tracing = "*"
uuid = {version = "*", features = ["v4"]}
