agent_connection_buffer_size = 65536
compress = false
ipv6 = false
port = 10081
proxy_addresses = ["127.0.0.1:9090"]
rsa_dir = "./resources/rsa/"
thread_number = 2048
user_token = "user1"
proxy_connection_number = 4
