agent_connection_accept_timeout = 2
compress = true
dest_tcp_framed_buffer_size = 65536
ipv6 = false
max_agent_connection_number = 65536
message_framed_buffer_size = 65536
port = 9090
proxy_server_worker_thread_number = 256
rsa_dir = "./resources/rsa/"
