agent_connection_accept_timeout = 20
compress = true
dest_connect_timeout = 20
dest_tcp_buffer_size = 524288
domain_name_resolve_tomeout = 20
ipv6 = false
max_agent_connection_number = 2048
message_framed_buffer_size = 524288
port = 80
proxy_server_worker_thread_number = 512
rsa_dir = "./resources/rsa/"
