agent_connection_accept_timeout = 20
compress = true
dst_connect_timeout = 20
dst_tcp_buffer_size = 524288
ipv6 = false
message_framed_buffer_size = 524288
port = 80
proxy_server_worker_thread_number = 512
rsa_dir = "./resources/rsa/"
