[package]
edition = "2021"
name = "ppaass-tool"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {workspace = true}
ppaass-common = {path = "../common"}
