agent_private_key_file = 'AgentPrivateKey.pem'
client_buffer_size = 2097152
client_stream_so_linger = 20
compress = true
init_proxy_connection_number = 64
max_blocking_threads = 128
message_framed_buffer_size = 2097152
min_proxy_connection_number = 32
port = 10080
proxy_addresses = [
  '149.28.219.182:80',
  '149.28.219.182:80',
  '149.28.219.182:80',
]
proxy_connection_check_interval_seconds = 20
proxy_connection_check_timeout = 2
proxy_connection_number_incremental = 16
proxy_public_key_file = 'ProxyPublicKey.pem'
proxy_stream_so_linger = 5
so_backlog = 2048
thread_number = 2048
thread_timeout = 10
user_token = 'user1'
