port = 10080
user_token = 'user1'
proxy_addresses = [
    '149.28.219.182:80',
    '149.28.219.182:80',
    '149.28.219.182:80',
]
client_buffer_size = 2097152
message_framed_buffer_size = 2097152
thread_number = 2048
max_blocking_threads = 128
thread_timeout = 10
compress = true
client_stream_so_linger = 20
proxy_stream_so_linger = 5
so_backlog = 2048
agent_private_key_file = 'AgentPrivateKey.pem'
proxy_public_key_file = 'ProxyPublicKey.pem'
init_proxy_connection_number = 64
min_proxy_connection_number = 32
proxy_connection_number_incremental = 16
proxy_connection_check_interval_seconds = 20
proxy_connection_check_timeout = 2
